kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1
  labels:
    app: wls-domain
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle  # Retain, Recycle, Delete
  #hostPath:
   # path: "/home/oracle/pv/pv1"
  nfs:
    #server: isilon.jxutcm.edu.cn
    #path: /ifs/OneCCP
    server: 172.17.20.25
    path: /nfs/weblogic
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv2
  labels:
    app: wls-domain
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle  # Retain, Recycle, Delete
  #hostPath:
    #path: "/home/oracle/pv/pv2"
  nfs:
    #server: isilon.jxutcm.edu.cn
    #path: /ifs/OneCCP
    server: 172.17.20.25
    path: /nfs/weblogic  

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv3
  labels:
    app: wls-domain
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle  # Retain, Recycle, Delete
  #hostPath:
    #path: "/home/oracle/pv/pv3"
  nfs:
    #server: isilon.jxutcm.edu.cn
    #path: /ifs/OneCCP
    server: 172.17.20.25
    path: /nfs/weblogic
